name: openRPG
version: "${version}"

main: org.lucma.openRPG.OpenRPG
paperPluginLoader: org.lucma.openRPG.OpenRPGLoader
api-version: "26.2"
load: POSTWORLD

authors: [Lucma]
website: lucma.dev

commands:
  openrpg:
    description: Comando principal de openRPG
    usage: |
      /<command> - Ayuda
      /<command> status - Estado del jugador
      /<command> class [id] - Seleccionar clase
      /<command> talent - Árbol de talentos
